=== biaogebusy/web-builder/src/app/uiux/combs/other/jsoneditor/schema/page.schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "$ref": "#/definitions/Page",
  "definitions": {
    "Page": {
      "type": "object",
      "additionalProperties": true,
      "properties": {
        "meta": {
          "type": "array",
          "items": {
            "type": "object"
          }
        },
        "config": {
          "type": "object"
        },
        "status": {
          "type": "boolean"
        },
        "message": {
          "type": "string"
        },
        "title": {
          "type": "string"
        },
        "uuid": {
          "type": "string",
          "format": "uuid"
        },
        "nid": {
          "type": "string"
        },
        "vid": {
          "type": "string"
        },
        "changed": {
          "type": "string"
        },
        "langcode": {
          "type": "string"
        },
        "label": {
          "type": "string"
        },
        "body": {
          "type": "array",
          "items": {
            "type": "object"
          }
        },
        "current": {
          "type": "boolean"
        },
        "dirty": {
          "type": "boolean"
        },
        "translation": {
          "type": "boolean"
        },
        "target": {
          "type": "string"
        },
        "time": {
          "type": ["string", "object"]
        }
      },
      "required": ["body", "title"],
      "title": "Page"
    }
  }
}

=== biaogebusy/web-builder/src/assets/app/sample/tmp.json
{
  "title": "\u7f51\u7edc\u76f4\u64ad\u76f8\u5173\u6cd5\u5f8b\u95ee\u9898\u6d45\u6790 | \u5a31\u4e50\u4f20\u5a92",
  "meta": [{
    "name": "description",
    "content": "\u4f5c\u8005|\u5434\u4eae\u738b\u76fc\u9633\u00a0\u5317\u4eac\u6da6\u521b\u5f8b\u5e08\u4e8b\u52a1\u6240"
  }],
  "config": {
    "node": {
      "entityId": "35"
    }
  },
  "body": [{
    "type": "article",
    "title": "\u7f51\u7edc\u76f4\u64ad\u76f8\u5173\u6cd5\u5f8b\u95ee\u9898\u6d45\u6790",
    "params": {
      "require_rule": ["vip"],
      "pay": {
        "money": 10
      }
    },
    "meta": [{
      "label": "\u53d1\u5e03",
      "value": "2021-12-21"
    }, {
      "label": "\u5206\u7c7b",
      "value": "\u76f4\u64ad"
    }, {
      "label": "\u5173\u952e\u5b57",
      "value": ""
    }],
    "body": "\u003Cp class=\u0022MsoNormal\u0022 data-text-indent=\u00222em\u0022 style=\u0022text-indent:2em\u0022\u003E\u003Cspan style=\u0022mso-spacerun:\u0027yes\u0027;font-family:\u0027Microsoft YaHei UI\u0027;letter-spacing:0.0000pt;font-weight:normal;text-transform:none;font-style:normal;font-size:11.0000pt;mso-font-kerning:1.0000pt;background:rgb(255,255,255);mso-shading:rgb(255,255,255);\u0022\u003E\u003Cfont face=\u0022Microsoft YaHei UI\u0022\u003E\u4f5c\u8005\u003C\/font\u003E | \u5434\u4eae \u738b\u76fc\u9633\u0026nbsp; \u5317\u4eac\u6da6\u521b\u5f8b\u5e08\u4e8b\u52a1\u6240\u003C\/span\u003E\u003Cspan style=\u0022mso-spacerun:\u0027yes\u0027;font-family:\u0027Microsoft YaHei UI\u0027;letter-spacing:0.0000pt;font-weight:normal;text-transform:none;font-style:normal;font-size:11.0000pt;mso-font-kerning:1.0000pt;background:rgb(255,255,255);mso-shading:rgb(255,255,255);\u0022\u003E\u003Co:p\u003E\u003C\/o:p\u003E\u003C\/span\u003E\u003C\/p\u003E\r\n\r\n\u003Cp class=\u0022MsoNormal\u0022 data-text-indent=\u00222em\u0022 style=\u0022text-indent:2em\u0022\u003E\u003Cspan style=\u0022mso-spacerun:\u0027yes\u0027;font-family:\u0027Microsoft YaHei UI\u0027;letter-spacing:0.0000pt;font-weight:normal;text-transform:none;font-style:normal;font-size:11.0000pt;mso-font-kerning:1.0000pt;background:rgb(255,255,255);mso-shading:rgb(255,255,255);\u0022\u003E\u003Co:p\u003E\u0026nbsp;\u003C\/o:p\u003E\u003C\/span\u003E\u003C\/p\u003E\r\n\r\n\u003Cp class=\u0022MsoNormal\u0022 data-text-indent=\u00222em\u0022 style=\u0022text-indent:2em\u0022\u003E\u003Cspan style=\u0022mso-spacerun:\u0027yes\u0027;font-family:\u0027Microsoft YaHei UI\u0027;letter-spacing:0.0000pt;font-weight:normal;text-transform:none;font-style:normal;font-size:11.0000pt;mso-font-kerning:1.0000pt;background:rgb(255,255,255);mso-shading:rgb(255,255,255);\u0022\u003E\u003Cfont face=\u0022Microsoft YaHei UI\u0022\u003E\u5728\u003C\/font\u003E\u201c\u4e92\u8054\u7f51\uff0b\u201d\u7684\u80cc\u666f\u4e4b\u4e0b\uff0c\u8fd1\u4e24\u5e74\u7f51\u7edc\u76f4\u64ad\u884c\u4e1a\u8fc5\u731b\u53d1\u5c55\uff0c\u51fa\u73b0\u4e86\u6620\u5ba2\u3001YY\u3001\u6597\u9c7c\u3001\u864e\u7259\u3001\u89e6\u624b\u3001\u718a\u732b\u3001\u82b1\u6912\u7b49\u76f4\u64ad\u5e73\u53f0\uff0c2016\u5e74\u66f4\u662f\u88ab\u76f4\u64ad\u4e1a\u5185\u79f0\u4e3a\u201c\u7f51\u7edc\u76f4\u64ad\u5143\u5e74\u201d\u3002\u7136\u800c\u4f55\u4e3a\u7f51\u7edc\u76f4\u64ad\u5462\uff1f\u6211\u4eec\u5148\u770b\u4e00\u4e0b\u6bd4\u8f83\u5b98\u65b9\u7684\u5b9a\u4e49\uff0c\u6839\u636e2016\u5e74\u300a\u4e92\u8054\u7f51\u76f4\u64ad\u670d\u52a1\u7ba1\u7406\u89c4\u5b9a\u300b\uff0c\u4e92\u8054\u7f51\u76f4\u64ad\u662f\u6307\u57fa\u4e8e\u4e92\u8054\u7f51\uff0c\u4ee5\u89c6\u9891\u3001\u97f3\u9891\u3001\u56fe\u6587\u7b49\u5f62\u5f0f\u5411\u516c\u4f17\u6301\u7eed\u53d1\u5e03\u5b9e\u65f6\u4fe1\u606f\u7684\u6d3b\u52a8\u3002\u7b80\u8a00\u4e4b\uff0c\u8fd9\u662f\u4e00\u79cd\u7531\u7f51\u7edc\u4e3b\u64ad\u901a\u8fc7\u76f4\u64ad\u5e73\u53f0\u8fdb\u884c\u6e38\u620f\uff0c\u7f8e\u5986\uff0c\u7f8e\u98df\uff0c\u6237\u5916\u7b49\u5185\u5bb9\u7684\u76f4\u64ad\u5e76\u4e0e\u7528\u6237\u5b9e\u65f6\u4e92\u52a8\u7684\u65b0\u578b\u7f51\u7edc\u5a31\u4e50\u65b9\u5f0f\uff0c\u5177\u6709\u5f88\u5f3a\u7684\u4ea4\u4e92\u6027\u3001\u5b9e\u65f6\u6027\u548c\u4fbf\u5229\u6027\u3002\u7f51\u7edc\u76f4\u64ad\u5185\u5bb9\u4e30\u5bcc\uff0c\u53d7\u5230\u5927\u4f17\u7684\u8ffd\u6367\uff0c\u5c24\u5176\u662f\u5728\u5f53\u524d\u79fb\u52a8\u8bbe\u5907\uff08\u667a\u80fd\u624b\u673a\uff0c\u5e73\u677f\u7535\u8111\uff09\u666e\u53ca\u7684\u60c5\u51b5\u4e0b\uff0c\u66f4\u662f\u5448\u73b0\u4e95\u55b7\u5f0f\u53d1\u5c55\u3002\u003C\/span\u003E\u003Cspan style=\u0022mso-spacerun:\u0027yes\u0027;font-family:\u0027Microsoft YaHei UI\u0027;letter-spacing:0.0000pt;font-weight:normal;text-transform:none;font-style:normal;font-size:11.0000pt;mso-font-kerning:1.0000pt;background:rgb(255,255,255);mso-shading:rgb(255,255,255);\u0022\u003E\u003Co:p\u003E\u003C\/o:p\u003E\u003C\/span\u003E\u003C\/p\u003E\r\n\r\n\u003Cp class=\u0022MsoNormal\u0022 data-text-indent=\u00222em\u0022 style=\u0022text-indent:2em\u0022\u003E\u003Cspan style=\u0022mso-spacerun:\u0027yes\u0027;font-family:\u0027Microsoft YaHei UI\u0027;letter-spacing:0.0000pt;font-weight:normal;text-transform:none;font-style:normal;font-size:11.0000pt;mso-font-kerning:1.0000pt;background:rgb(255,255,255);mso-shading:rgb(255,255,255);\u0022\u003E\u003Cfont face=\u0022Microsoft YaHei UI\u0022\u003E\u6839\u636e\u300a\u003C\/font\u003E2017\u5e74\u7f51\u7edc\u76f4\u64ad\u884c\u4e1a\u53d1\u5c55\u62a5\u544a\u300b\u663e\u793a\uff1a\u201c2017\u5e74\u6211\u56fd\u7f51\u7edc\u8868\u6f14\u5e02\u573a\u8425\u6536\u8fbe\u5230304.5\u4ebf\u5143\uff0c\u76f8\u6bd42016\u5e74\u7684218.5\u4ebf\u5143\uff0c\u540c\u6bd4\u589e\u957f39%\u3002\u7f51\u7edc\u8868\u6f14\u5df2\u7ecf\u6210\u4e3a\u7f51\u7edc\u6587\u5316\u5185\u5bb9\u4f9b\u5e94\u3001\u6280\u672f\u521b\u65b0\u3001\u5546\u4e1a\u6a21\u5f0f\u521b\u65b0\u7684\u4ee3\u8868\uff0c\u6210\u4e3a\u7f51\u7edc\u6587\u5316\u5e02\u573a\u91cd\u8981\u7ec4\u6210\u90e8\u5206\u3002\u76f4\u64ad\u884c\u4e1a\u4e0e\u5176\u4ed6\u4ea7\u4e1a\u7684\u8054\u52a8\u65e5\u76ca\u7d27\u5bc6\uff0c\u201c\u76f4\u64ad+\u201d\u6a21\u5f0f\u9010\u6e10\u6210\u578b\u2026\u2026\u76f4\u64ad\u5e73\u53f0\u63d0\u4f9b\u7684\u5185\u5bb9\u548c\u7f51\u7edc\u6e38\u620f\u3001\u7f51\u7edc\u97f3\u4e50\u3001\u7f51\u7edc\u6587\u5b66\u3001\u7f51\u7edc\u89c6\u9891\u7b49\u7f51\u7edc\u6587\u5316\u5f62\u5f0f\u4e00\u6837\uff0c\u5f97\u5230\u4e86\u7528\u6237\u7684\u5e7f\u6cdb\u4f7f\u7528\uff0c\u6210\u4e3a\u7f51\u6c11\u6587\u5316\u5a31\u4e50\u6d88\u8d39\u7684\u91cd\u8981\u5f62\u5f0f\u3002\u201d2018\u5e74CNNIC\u300a\u4e2d\u56fd\u4e92\u8054\u7f51\u7edc\u53d1\u5c55\u72b6\u51b5\u7edf\u8ba1\u62a5\u544a\u300b\u663e\u793a\uff1a\u201c\u622a\u81f32018\u5e746\u6708\uff0c\u6211\u56fd\u7f51\u7edc\u76f4\u64ad\u7528\u6237\u89c4\u6a21\u8fbe\u52304.25\u4ebf\uff0c\u8f832017\u5e74\u672b\u5fae\u589e294\u4e07\uff0c\u7528\u6237\u4f7f\u7528\u7387\u4e3a53.0\uff05\uff0c\u8f832017\u5e74\u4e0b\u964d1.7\u4e2a\u767e\u5206\u70b9\u201d\u3002\u8db3\u89c1\u7f51\u7edc\u76f4\u64ad\u5df2\u7ecf\u6210\u4e3a\u4e00\u79cd\u91cd\u8981\u7684\u5927\u4f17\u6587\u5316\u5a31\u4e50\u6d88\u8d39\u5e73\u53f0\uff0c\u4e3a\u7f51\u7edc\u6587\u5316\u5e02\u573a\u7684\u53d1\u5c55\u5e26\u6765\u65b0\u7684\u5546\u673a\u3002\u5404\u7c7b\u9020\u661f\u9020\u5bcc\u795e\u8bdd\u5c42\u51fa\uff0c\u5982\uff0c\u201c\u5c40\u5ea7\u201d\u5728B\u7ad9\u76f4\u64ad2\u5c0f\u65f6\u5728\u7ebf\u4eba\u6570\u4e00\u5ea6\u8d85\u8fc775\u4e07\u4eba\uff0c\u83b7\u7c89\u65e0\u6570\uff1b\u4f5c\u4e3a\u8dd1\u7537\u56e2\u6210\u5458\u4e4b\u4e00\u7684\u738b\u7956\u84dd\uff0c\u4ec5\u4ec5\u662f\u4e24\u4e2a\u5c0f\u65f6\u7684\u76f4\u64ad\u65f6\u95f4\u5185\uff0c\u5c31\u6536\u5230\u4e86\u7ea6300\u4e07\u5143\u7684\u793c\u7269\u6253\u8d4f\uff1b\u738b\u8005\u8363\u8000\u4e00\u7ebf\u4e3b\u64ad\u5251\u4ed9\u7684\u5e74\u6536\u5165\u88ab\u7206\u51fa\u9ad8\u8fbe\u5343\u4e07\u3002\u7f51\u7edc\u76f4\u64ad\u4f5c\u4e3a\u4e00\u79cd\u65b0\u5174\u7684\u7f51\u7edc\u4ea7\u4e1a\uff0c\u5728\u4e00\u7247\u7e41\u534e\u7684\u80cc\u540e\uff0c\u4e5f\u6ecb\u751f\u4e86\u5f88\u591a\u4e71\u8c61\u548c\u4e9f\u5f85\u6cd5\u5f8b\u89c4\u5236\u7684\u95ee\u9898\uff0c\u6bd4\u5982\u7f51\u7edc\u76f4\u64ad\u5185\u5bb9\u4f4e\u4fd7\u3001\u6d89\u9ec4\u3001\u6d89\u66b4\uff1b\u5404\u7f51\u7edc\u5e73\u53f0\u4e4b\u95f4\u65e0\u5e8f\u7ade\u4e89\uff1b\u7f51\u7edc\u76f4\u64ad\u5185\u5bb9\u4fb5\u72af\u4ed6\u4eba\u6743\u76ca\u7b49\u3002\u63a5\u4e0b\u6765\u7b14\u8005\u5c31\u9488\u5bf9\u76ee\u524d\u7f51\u7edc\u76f4\u64ad\u4e2d\u6d89\u53ca\u7684\u4e3b\u8981\u6cd5\u5f8b\u95ee\u9898\u8fdb\u884c\u7b80\u5355\u7684\u5f52\u7eb3\u548c\u5206\u6790\u3002\u003C\/span\u003E\u003Cspan style=\u0022mso-spacerun:\u0027yes\u0027;font-family:\u0027Microsoft YaHei UI\u0027;letter-spacing:0.0000pt;font-weight:normal;text-transform:none;font-style:normal;font-size:11.0000pt;mso-font-kerning:1.0000pt;background:rgb(255,255,255);mso-shading:rgb(255,255,255);\u0022\u003E\u003Co:p\u003E\u003C\/o:p\u003E\u003C\/span\u003E\u003C\/p\u003E\r\n\r\n\u003Cp class=\u0022MsoNormal\u0022 data-text-indent=\u00222em\u0022 style=\u0022text-indent:2em\u0022\u003E\u003Cspan style=\u0022mso-spacerun:\u0027yes\u0027;font-family:\u0027Microsoft YaHei UI\u0027;letter-spacing:0.0000pt;font-weight:normal;text-transform:none;font-style:normal;font-size:11.0000pt;mso-font-kerning:1.0000pt;background:rgb(255,255,255);mso-shading:rgb(255,255,255);\u0022\u003E\u003Cfont face=\u0022Microsoft YaHei UI\u0022\u003E\u4e00\u003C\/font\u003E\u003C\/span\u003E\u003Cspan style=\u0022mso-spacerun:\u0027yes\u0027;font-family:\u0027Microsoft YaHei UI\u0027;letter-spacing:0.0000pt;font-weight:normal;text-transform:none;font-style:normal;font-size:11.0000pt;mso-font-kerning:1.0000pt;background:rgb(255,255,255);mso-shading:rgb(255,255,255);\u0022\u003E\u0026nbsp;\u003C\/span\u003E\u003Cspan style=\u0022mso-spacerun:\u0027yes\u0027;font-family:\u0027Microsoft YaHei UI\u0027;letter-spacing:0.0000pt;font-weight:normal;text-transform:none;font-style:normal;font-size:11.0000pt;mso-font-kerning:1.0000pt;background:rgb(255,255,255);mso-shading:rgb(255,255,255);\u0022\u003E\u003Cfont face=\u0022Microsoft YaHei UI\u0022\u0
